### ISSUE TITLE
[Feature Request] 增加自訂同步天數或類似功能

### ISSUE THREAD

**Issue by fanlan1210** [gnehs/StepStep-RN#3]
在長期使用 Android 版餅餅踏踏後，發現有一個不方便的地方還是需要克服，主要就是 App 本身的後台還是有機會被系統停止，這時候就需要回去 App 手動同步觸發一次。

但問題就來了，如果好一陣子沒有發現，等於資料就會遺漏無法回補，而目前 App 本身只有 1、3、7 天的同步資料功能，希望能夠增加自訂天數的同步功能，或甚至新增一個「從最後一次自動同步開始起算」的同步功能。

附註：既然自己開了這個 issue，我可能也有機會自己填這個坑XD

**Comment by gnehs** [comment]
我刻意限制同步長度最長為七天的原因是不想破壞已有的排行榜，若是開放無限制的資料上傳的話，可能會導致排名大幅度更動，我想避免這種情況發生。

雖然目前伺服器端並沒有限制資料上傳數量就是了

**Comment by fanlan1210** [comment]
> 我刻意限制同步長度最長為七天的原因是不想破壞已有的排行榜，若是開放無限制的資料上傳的話，可能會導致排名大幅度更動，我想避免這種情況發生。
> 
> 雖然目前伺服器端並沒有限制資料上傳數量就是了
> 

了解！那感覺設計的方向可以朝限制在七天這個範圍進行

**Comment by fanlan1210** [comment]
好耶，merge 了，自行填坑完畢，也要感謝勝勝 @gnehs 在過程中提供的建議ouo
